version: '2'

services:
  contacto-mysql:
    container_name: contacto-mysql
    build:
      context: .
      dockerfile: Dockerfile-mysql
    restart: always

  contacto-app:
    container_name: contacto-app
    build:
      context: .
      dockerfile: Dockerfile-app
    depends_on:
      - contacto-mysql
    ports:
      - "3000:3000"
    restart: always
